#!/bin/bash
#
# Copyright (c) 2018, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Imports a WARC file into a repository.

# This script expects the following arguments:
#
# One of:
#   -l some_filesystem_directory
#   The directory with the local repository where to import the WARC.
# or:
#   -r http://some_host:some_port
#   The location of the REST Repository Service where to import the WARC.
#
# -c some_collectionName
# The name of the collection where to import the WARC.
#
# -a 'some_auId'
# The Archival Unit identifier where to import the WARC.
#
# some_WARC
# The name of the file with the WARC to be imported

# Get the file specification of this script.
SOURCE="${BASH_SOURCE[0]}"

# Handle symbolic links.
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

# Get the absolute path to the directory where this script resides.
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Change to the directory where the pom.xml file resides.
cd $DIR/..

# Run the WARCImporter program.
mvn exec:java -Drun.mainClass=org.lockss.laaws.rs.client.WARCImporter -Drun.args="$1,$2,$3,$4,$5,$6,$7"
