#!/bin/sh
#
# Copyright (c) 2018, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Imports a WARC file into a REST Repository Service.

# This script expects the following arguments:
#
# -r http://some_host:some_port
# The location of the REST Repository Service where to import the WARC.
#
# -c some_collectionName
# The name of the collection where to import the WARC.
#
# -a 'some_auId'
# The Archival Unit identifier where to import the WARC.
#
# some_WARC
# The name of the file with the WARC to be imported

export M2_HOME=$HOME/.m2/repository
export CLASS_PATH=\
$M2_HOME/org/lockss/laaws/laaws-repository-client/1.1.0/laaws-repository-client-1.1.0.jar\
:$M2_HOME/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar\
:$M2_HOME/commons-cli/commons-cli/1.2/commons-cli-1.2.jar\
:$M2_HOME/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar\
:$M2_HOME/org/springframework/spring-core/4.3.13.RELEASE/spring-core-4.3.13.RELEASE.jar\
:$M2_HOME/org/springframework/spring-web/4.3.13.RELEASE/spring-web-4.3.13.RELEASE.jar\
:$M2_HOME/org/netpreserve/commons/webarchive-commons/1.1.8/webarchive-commons-1.1.8.jar\
:$M2_HOME/commons-io/commons-io/2.4/commons-io-2.4.jar\
:$M2_HOME/commons-lang/commons-lang/2.5/commons-lang-2.5.jar\
:$M2_HOME/com/google/guava/guava/18.0/guava-18.0.jar\
:$M2_HOME/it/unimi/dsi/fastutil/6.5.2/fastutil-6.5.2.jar\
:$M2_HOME/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar\
:$M2_HOME/org/lockss/laaws/laaws-repository-common/1.1.0/laaws-repository-common-1.1.0.jar\
:$M2_HOME/com/fasterxml/jackson/core/jackson-core/2.8.10/jackson-core-2.8.10.jar\
:$M2_HOME/com/fasterxml/jackson/core/jackson-databind/2.8.10/jackson-databind-2.8.10.jar\
:$M2_HOME/org/springframework/spring-beans/4.3.13.RELEASE/spring-beans-4.3.13.RELEASE.jar\
:$M2_HOME/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar

java -cp $CLASS_PATH org.lockss.laaws.rs.client.WARCImporter $@
